#!/usr/bin/python

import json
import sys
import subprocess
import zipfile

if len(sys.argv) < 2:
    print >> sys.stderr, "idraw2json  idraw-file"
    sys.exit(1)
    
    
idraw = zipfile.ZipFile(sys.argv[1], "r")
plist = idraw.open("data.xml")
file(sys.argv[1] + ".plist", "w+").write(plist.read())
plist.close()
idraw.close()
